# Generated by Django 5.0.2 on 2024-03-03 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Composer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "composer",
            },
        ),
        migrations.CreateModel(
            name="Conductor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "conducter",
            },
        ),
        migrations.CreateModel(
            name="Orchestra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "orchestra",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("instrument", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "player",
            },
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("semester_num", models.IntegerField()),
                ("total_time", models.IntegerField(default=4)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("rest_time", models.IntegerField(default=10)),
            ],
            options={
                "db_table": "semester",
            },
        ),
        migrations.CreateModel(
            name="TimeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.IntegerField()),
                ("date", models.DateField()),
                ("arrival_time", models.TimeField()),
                ("mentee_arrival_time", models.TimeField(blank=True, null=True)),
                (
                    "time_comment_music",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "time_comment_gigi",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "time_comment_etc",
                    models.TextField(blank=True, default="", null=True),
                ),
            ],
            options={
                "db_table": "time",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("major", models.CharField(max_length=40)),
                ("year_id", models.CharField(max_length=2)),
                ("is_ob", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Music",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "composer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musics",
                        to="time_manage.composer",
                    ),
                ),
            ],
            options={
                "db_table": "music",
            },
        ),
        migrations.CreateModel(
            name="MusicDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semi_title", models.CharField(max_length=200)),
                (
                    "music",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="time_manage.music",
                    ),
                ),
            ],
            options={
                "db_table": "music_detail",
            },
        ),
        migrations.CreateModel(
            name="TimeMusic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("is_requested", models.BooleanField(default=False)),
                ("source", models.CharField(max_length=20)),
                ("cd_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "conductor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_manage.conductor",
                    ),
                ),
                (
                    "music",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_manage.music",
                    ),
                ),
                (
                    "music_detail",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_manage.musicdetail",
                    ),
                ),
                (
                    "orchestra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_manage.orchestra",
                    ),
                ),
                ("players", models.ManyToManyField(to="time_manage.player")),
                (
                    "time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_manage.timeinfo",
                    ),
                ),
            ],
            options={
                "db_table": "time_music",
            },
        ),
        migrations.AddField(
            model_name="timeinfo",
            name="mentee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentee_time",
                to="time_manage.user",
            ),
        ),
        migrations.AddField(
            model_name="timeinfo",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time",
                to="time_manage.user",
            ),
        ),
        migrations.CreateModel(
            name="SemesterUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField()),
                ("time", models.IntegerField()),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userinfo",
                        to="time_manage.semester",
                    ),
                ),
                (
                    "mentee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menteesemesterinfo",
                        to="time_manage.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usersemesterinfo",
                        to="time_manage.user",
                    ),
                ),
            ],
            options={
                "db_table": "semester_user",
            },
        ),
    ]
