# Generated by Django 4.2.4 on 2023-12-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComposerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "composer_info",
            },
        ),
        migrations.CreateModel(
            name="ConductorInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "conducter_info",
            },
        ),
        migrations.CreateModel(
            name="OrchestraInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "orchestra_info",
            },
        ),
        migrations.CreateModel(
            name="PlayerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("instrument", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "player_info",
            },
        ),
        migrations.CreateModel(
            name="SemesterInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("semester", models.IntegerField()),
                ("total_time", models.IntegerField(default=4)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("rest_time", models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("major", models.CharField(max_length=40)),
                ("year_id", models.CharField(max_length=2)),
                ("is_ob", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="TimeInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.IntegerField()),
                ("date", models.DateField()),
                ("arrival_time", models.TimeField()),
                ("mentee_arrival_time", models.TimeField(blank=True, null=True)),
                (
                    "time_comment_music",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "time_comment_gigi",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "time_comment_etc",
                    models.TextField(blank=True, default="", null=True),
                ),
                (
                    "SemesterInfo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeinfo",
                        to="time_manage.semesterinfo",
                    ),
                ),
                (
                    "mentee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentee_time",
                        to="time_manage.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time",
                        to="time_manage.user",
                    ),
                ),
            ],
            options={
                "db_table": "time_info",
            },
        ),
        migrations.CreateModel(
            name="SemesterUserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField()),
                ("time", models.IntegerField()),
                (
                    "mentee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menteesemesterinfo",
                        to="time_manage.user",
                    ),
                ),
                (
                    "semester_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userinfo",
                        to="time_manage.semesterinfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usersemesterinfo",
                        to="time_manage.user",
                    ),
                ),
            ],
            options={
                "db_table": "semester_user_info",
            },
        ),
        migrations.CreateModel(
            name="MusicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_requested", models.BooleanField(default=False)),
                ("source", models.CharField(max_length=20)),
                ("cd_id", models.CharField(blank=True, max_length=20, null=True)),
                ("title", models.CharField(max_length=200)),
                ("semi_title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "composer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="musics",
                        to="time_manage.composerinfo",
                    ),
                ),
                (
                    "conductor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_manage.conductorinfo",
                    ),
                ),
                (
                    "orchestra",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_manage.orchestrainfo",
                    ),
                ),
                ("players", models.ManyToManyField(to="time_manage.playerinfo")),
                (
                    "time_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="time_manage.timeinfo",
                    ),
                ),
            ],
            options={
                "db_table": "music_info",
            },
        ),
    ]
