# Generated by Django 4.2.4 on 2024-03-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_manage", "0002_alter_timemusic_time"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timeinfo",
            unique_together={("time", "date")},
        ),
    ]
