# Generated by Django 4.2.4 on 2024-06-30 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("time_manage", "0003_alter_timeinfo_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table", models.JSONField()),
                (
                    "semester",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable",
                        to="time_manage.semester",
                    ),
                ),
            ],
            options={
                "db_table": "timetable",
            },
        ),
        migrations.CreateModel(
            name="TimetableUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.IntegerField()),
                ("time", models.IntegerField()),
                (
                    "mentee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menteesemestertimeinfo",
                        to="time_manage.user",
                    ),
                ),
                (
                    "timetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="time_manage.timetable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usersemestertimeinfo",
                        to="time_manage.user",
                    ),
                ),
            ],
            options={
                "db_table": "timetable_unit",
            },
        ),
    ]
