# Generated by Django 4.2.4 on 2024-06-30 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("time_manage", "0005_alter_timetable_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetableunit",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usersemestertimeinfo",
                to="time_manage.user",
            ),
        ),
    ]
