# Generated by Django 4.2.4 on 2024-07-02 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("time_manage", "0006_alter_timetableunit_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sabu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jejas",
                to="time_manage.user",
            ),
        ),
    ]
