# Generated by Django 4.2.4 on 2024-07-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_manage", "0007_user_sabu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="sabu",
            new_name="sabu_id",
        ),
    ]
