# Generated by Django 4.2.4 on 2024-08-10 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_manage", "0008_rename_sabu_user_sabu_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("year", "semester_num")},
        ),
    ]
