# Generated by Django 4.2.4 on 2024-08-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_manage", "0009_alter_semester_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timetableunit",
            unique_together={("timetable", "day", "time")},
        ),
    ]
