# Generated by Django 4.2.4 on 2024-08-27 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("time_manage", "0011_user_join_semester_user_join_year"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-join_year", "-join_semester", "-year_id"]},
        ),
    ]
