# Generated by Django 4.2.4 on 2025-03-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_manage", "0012_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=100)),
            ],
            options={
                "db_table": "news",
            },
        ),
    ]
