# Generated by Django 4.2.4 on 2025-08-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("time_manage", "0013_news"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetableunit",
            name="mentee",
        ),
        migrations.RemoveField(
            model_name="timetableunit",
            name="user",
        ),
        migrations.AddField(
            model_name="timetableunit",
            name="mentees",
            field=models.ManyToManyField(
                blank=True, related_name="menteesemestertimeinfo", to="time_manage.user"
            ),
        ),
        migrations.AddField(
            model_name="timetableunit",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="usersemestertimeinfo", to="time_manage.user"
            ),
        ),
    ]
